-- Task-03 --
-- 1.1 --
SELECT * FROM Pessoa p
RIGHT JOIN Contato c ON (p.id_pessoa = c.ID_PESSOA)

-- 1.2 --
SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO ppe ON (ppe.ID_PESSOA = p.ID_PESSOA)
RIGHT JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = ppe.ID_ENDERECO)

-- 1.3 --
SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO ppe ON (ppe.ID_PESSOA = p.ID_PESSOA)
RIGHT JOIN ENDERECO e ON (e.ID_ENDERECO = ppe.ID_ENDERECO)
RIGHT JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = ppe.ID_ENDERECO)
RIGHT JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA)

-- 2.1 --
SELECT * FROM Pessoa p
FULL JOIN Contato c ON (p.id_pessoa = c.ID_PESSOA)

-- 2.2 --
SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO ppe ON (ppe.ID_PESSOA = p.ID_PESSOA)
FULL JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = ppe.ID_ENDERECO)

-- 2.3 --
SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO ppe ON (ppe.ID_PESSOA = p.ID_PESSOA)
FULL JOIN ENDERECO e ON (e.ID_ENDERECO = ppe.ID_ENDERECO)
FULL JOIN ENDERECO_PESSOA ep ON (ep.ID_ENDERECO = ppe.ID_ENDERECO)
FULL JOIN CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA)



-- 3.0 --
SELECT * FROM pessoa p
	WHERE EXISTS (
		SELECT * FROM PESSOA_X_PESSOA_ENDERECO ppe
		WHERE p.ID_PESSOA = ppe.ID_PESSOA 
	);


-- 4.0 --
SELECT p.ID_PESSOA, p.NOME 
	FROM PESSOA p
UNION
SELECT en.ID_ENDERECO, en.logradouro 
	FROM ENDERECO en
