CREATE TABLE ENDERECO (
	id_endereco NUMBER(38, 0) NOT NULL,
	id_bairro NUMBER(38, 0) NOT NULL,
	id_cidade number(38, 0) NOT NULL,
	logradouro VARCHAR2(255) NOT NULL,
	numero NUMBER(38, 0) NOT NULL,
	complemento VARCHAR2(100),
	cep CHAR(9),
	PRIMARY KEY (id_endereco)
);

CREATE SEQUENCE VEM_SER.SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


CREATE TABLE BAIRRO (
	id_bairro NUMBER(38, 0) NOT NULL, 
	id_cidade NUMBER(38, 0) NOT NULL,
	id_estado NUMBER(38, 0) NOT NULL,
	nome VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_BAIRRO_CIDADE PRIMARY KEY (id_bairro, id_cidade),
	CONSTRAINT FK_CIDADE FOREIGN KEY (id_cidade, id_estado) REFERENCES CIDADE(id_cidade, id_estado),
	CONSTRAINT FK_BAIRRO_ESTADO FOREIGN KEY (id_estado) REFERENCES ESTADO
);

CREATE SEQUENCE VEM_SER.SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE CIDADE (
	id_cidade NUMBER(38, 0) NOT NULL,
	id_estado NUMBER(38, 0) NOT NULL,
	nome VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_CIDADE_ESTADO PRIMARY KEY (id_cidade, id_estado),
	CONSTRAINT FK_ESTADO FOREIGN KEY (id_estado) REFERENCES ESTADO
);

CREATE SEQUENCE VEM_SER.SEQ_CiDADE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE ESTADO (
	id_estado NUMBER(38, 0) NOT NULL,
	id_pais NUMBER(38, 0) NOT NULL,
	nome VARCHAR2(50) NOT NULL,
	PRIMARY KEY (id_estado)
);

CREATE SEQUENCE VEM_SER.SEQ_ESTADO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE PAIS (
	id_pais NUMBER(38, 0) NOT NULL,
	nome VARCHAR2(50) NOT NULL,
	PRIMARY KEY (id_pais)
);

CREATE SEQUENCE VEM_SER.SEQ_PAIS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- 2 INSERTS PAÍS --
INSERT INTO PAIS (id_pais, NOME)
VALUES (SEQ_PAIS.NEXTVAL, 'Brasil');

INSERT INTO PAIS (id_pais, NOME)
VALUES (SEQ_PAIS.NEXTVAL, 'Moçambique');


-- 2 INSERTS ESTADO --
INSERT INTO estado(ID_ESTADO, ID_PAIS, NOME)
VALUES (SEQ_ESTADO.NEXTVAL, 1, 'Paraíba');

INSERT INTO estado(ID_ESTADO, ID_PAIS, NOME)
VALUES (SEQ_ESTADO.NEXTVAL, 2, 'Niassa');


-- 2 INSERTS CIDADE --
INSERT INTO CIDADE(ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_CIDADE.NEXTVAL, 1, 'Conceição');

INSERT INTO CIDADE(ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_CIDADE.NEXTVAL, 2, 'Mandimba');


-- 2 INSERTS BAIRRO --
INSERT INTO BAIRRO(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_BAIRRO.NEXTVAL, 1, 1, 'João Juvenal');

INSERT INTO BAIRRO(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES (SEQ_BAIRRO.NEXTVAL, 2, 2, 'Distrito homónimo');

SELECT * FROM bairro;

-- 2 INSERTS ENDERECO -- 
INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Rua João Juvenal', 0, 'Descobrindo', '59028300');

INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 2, 2, 'Não existe', 0, 'Não há', '32142303');

INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Amacaté', 0, 'De frente ao salão de beleza', '32132213');

INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Tocambó', 155, 'Onde não bate luz', '12324115');


INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Chambra', 85, 'Rua da prata', '12323110');


INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Banca', 23, 'Rua da nova', '17283110');


INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Rua otávio', 31, 'Olimpic', '17453137');


INSERT INTO ENDERECO(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES(SEQ_ENDERECO.NEXTVAL, 1, 1, 'Rua Blamba', 31, 'Olimpic', '11111111');


-- TESK-01 --
-- Ordem decrescente dos nomes: --
SELECT * FROM PAIS ORDER BY nome DESC;

-- Logragouros de cep filtrados por a% --
SELECT logradouro, cep FROM endereco
WHERE lower(logradouro) LIKE 'a%'

-- Todos os endereços com cep com final 0 --
SELECT * FROM endereco
WHERE TRIM(CEP) LIKE '%0'

-- Todos os endereços que tenham numero entre 1 e 100 --
SELECT * FROM ENDERECO
WHERE numero > 0 AND numero < 101

-- Todos os enderecos que comecem com "Rua" e ordenação por cep DESC --
SELECT * FROM ENDERECO
WHERE lower(LOGRADOURO) LIKE 'rua%'
ORDER BY CEP DESC 

-- Quantidade de enderecos cadastrados na tablela --
SELECT COUNT(*) AS Quantidade_Enderecos FROM ENDERECO

-- Quantidade de enderecos cadastrados agrupados pelo id na cidade --
SELECT COUNT(*) AS Quantidade_enderecos_Conceicao FROM CIDADE e, Endereco en
WHERE e.ID_CIDADE = 1 AND en.ID_CIDADE = 1




